apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: angular-deployment3
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: sanju09/repo45 # Image that will be used to containers in the cluster
        ports:
        - containerPort: 80 # The port that the container is running on in the cluster
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: angular-service3
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80   # The port that the service is running on in the cluster
    targetPort: 80   # The port exposed by the service
    nodePort: 30007
  type: NodePort     # type of the service.