apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: angulardeployment4
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: sanju09/repo45 # Image that will be used to containers in the cluster
        imagPullPoilicy: IfNotPresent
        ports:
        - containerPort: 80 # The port that the container is running on in the cluster
---


apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: angularservice4
spec:
  selector:
    app: angular
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      nodePort: 27000
  type: NodePort # type of the service.